export enum EQuestionType {
  MULTIPLE_LISTENING = "MULTIPLE_LISTENING",
  SINGLE_LISTENING = "SINGLE_LISTENING",
  PARAGRAPH_READING = "PARAGRAPH_READING",
  SENTENCE_READING = "SENTENCE_READING",
}
